stages:
  process:
    cmd: python process_data.py
    deps:
      - data_raw.csv
      - process_data.py
    outs:
      - data_processed.csv
  train:
    cmd: python train.py
    deps:
      - train.py
      - data_processed.csv
    outs:
      - by_region.png
    metrics:
      - metrics.json:
          cache: false