name: dvc-cml
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.CML_GITHUB_ACCESS_TOKEN }}
        run: |
          pip install -r requirements.txt
          dvc repro

          git fetch --prune
          dvc metrics diff master --show-md >> report.md

          echo "## Validating results by region" >> report.md
          echo "![](./by_region.png)" >> report.md
          cml comment create report.md